<a href="https://colab.research.google.com/github/beshoynashaat/synent-task1-datacleaning-beshoynashaat/blob/main/synent_task1_datacleaning_beshoynashaat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import seaborn as sns

# Load the Titanic dataset
df = sns.load_dataset('titanic')

print('Initial Data Shape:', df.shape)
display(df.head())

Initial Data Shape: (891, 15)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### 1. Handling Missing Values

In [12]:
# Check for missing values
print('Missing values per column:\n', df.isnull().sum())

# Fill 'age' with the median
df['age'] = df['age'].fillna(df['age'].median())

# Drop 'deck' since it has too many missing values
if 'deck' in df.columns:
    df = df.drop(columns=['deck'])

# Fill 'embarked' and 'embark_town' with the mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

print("\nMissing Values is Filled")
print('\nMissing values after cleaning:\n', df.isnull().sum())

Missing values per column:
 survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Missing Values is Filled

Missing values after cleaning:
 survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

### 2. Remove Duplicates, Convert Data Types, and Rename Columns

In [13]:
# Remove duplicates
duplicates_count = df.duplicated().sum()
print(f'Number Of Duplicated columns: {duplicates_count}')
df = df.drop_duplicates()
print(f'Removed {duplicates_count} duplicate rows.')

# Convert data types (e.g., ensuring 'survived' is an integer/category)
df['survived'] = df['survived'].astype(int)

# Rename columns for clarity
df = df.rename(columns={
    'pclass': 'passenger_class',
    'sibsp': 'siblings_spouses',
    'parch': 'parents_children'
})

print('\nFinal columns:', df.columns.tolist())
display(df.head())

Number Of Duplicated columns: 116
Removed 116 duplicate rows.

Final columns: ['survived', 'passenger_class', 'sex', 'age', 'siblings_spouses', 'parents_children', 'fare', 'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive', 'alone']

,survived,passenger_class,sex,age,siblings_spouses,parents_children,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True